name: Generate data

on: [push]

env:
  PYTHON_VERSION: 3.12
  PYTHON_MAIN: ./work.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - id: cache-outputs
        uses: actions/cache@v1
        with:
          path: ./out
          key: ${{ runner.os }}-generated-${{ hashFiles('data/*.pdf', env.PYTHON_MAIN) }}
      - name: Run processing
        run: pipenv run python ${{ env.PYTHON_MAIN }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-data
          path: ./out
